# REPASO BÁSICO DE ESTADÍSTICA Y ÁLGEBRA MATRICIAL

## REVISIÓN DE LOS DATOS 

Antes de iniciar cualquier análisis es fundamental conocer los datos que se van a utilizar, por ello a continuación se muestran algunas formas para su descripción. 
 
a) Localización 
 
La medida de localización más usual es la media aritmética de una muestra. 
 
Para ejemplificar esta medida tomamos los datos del cuadro 1 que corresponden al Producto Interno Bruto de los estados mexicanos (en este archivo las variables que están en las columnas son los estados) y que se encuentran en el archivo pib_estados.txt.

In [1]:
pib_estados2 = read.table("pib_estados2.txt", header = TRUE, sep="", na.strings="NA", dec=".", strip.white=TRUE, row.names = "Estado")
# 

In [2]:
pib_estados2

AGS       BC       BCS      CAM      COAH     COL      CHIS     CHIH    
PIB03  98383.74 306256.5 60816.63 884335.8 326752.1 58017.41 199555.4 275023.2
PIB04 103894.08 324534.4 68511.61 892620.0 339038.7 59090.04 194308.5 289514.9
PIB05 107255.25 338789.5 74692.13 871645.0 346050.5 60307.88 195008.2 305203.7
PIB06 116347.08 359606.3 81223.51 852902.2 362581.1 63465.46 202567.2 328518.1
PIB07 126396.49 371491.4 87956.60 799534.9 376366.5 67373.23 199816.0 339605.4
PIB08 127431.78 371518.5 91013.49 753115.2 381450.9 69265.01 207208.9 346716.6
PIB09 121576.43 341058.8 86457.95 683450.2 332801.3 65112.38 204472.3 319604.9
PIB10 130349.51 348515.6 89565.26 653919.3 382712.4 67669.75 220648.9 323411.3
PIB11 135780.72 364799.8 94140.27 632560.6 413397.3 72700.17 227138.2 329662.5
      DF      DGO      ... QROO     SLP      SIN      SON      TAB     
PIB03 1710592 128611.2 ... 129318.4 179387.9 210806.9 260880.7 286218.3
PIB04 1782075 132458.1 ... 139331.0 190574.6 223131.2 272877.1 298905.0
PIB05 1830743 132675.0 ... 147659.2 197195.2 228525.5 288754.1 321926.2
PIB06 1933232 138464.3 ... 155184.4 207511.9 236184.3 310843.9 342674.1
PIB07 1990454 143148.4 ... 171021.7 212939.5 248751.0 321422.2 354244.5
PIB08 2029147 142855.4 ... 179545.4 220474.6 257363.4 320904.0 367560.1
PIB09 1949102 138472.6 ... 168909.5 211277.1 245369.7 309016.7 381685.9
PIB10 2033882 143300.3 ... 175043.5 224958.7 255376.5 330705.1 403753.8
PIB11 2116151 149343.0 ... 185014.7 238039.2 251035.5 353109.0 423990.5
      TAM      TLAX     VER      YUC      ZAC      
PIB03 320815.3 59722.77 503513.3 138897.7  81477.37
PIB04 336119.5 62328.30 531119.6 145131.9  85268.08
PIB05 356651.1 58585.55 548746.2 152874.9  85227.46
PIB06 363221.1 62902.64 586419.2 162442.4  91834.15
PIB07 377823.5 63524.60 611093.0 168459.0  93372.99
PIB08 390300.6 65220.52 613920.7 172135.2  98072.97
PIB09 372229.2 62695.69 610175.1 168483.1 104566.35
PIB10 382636.6 66701.31 634285.7 175363.2 115378.29
PIB11 384890.4 69808.87 649290.6 180047.8 117601.87

La medida de localización más usual es la media aritmética de una muestra. 
 
Para ejemplificar esta medida tomamos los datos del cuadro 1 que corresponden al Producto Interno Bruto de los estados mexicanos (en este archivo las variables que están en las columnas son los estados) y que se encuentran en el archivo pib_estados.txt. Considerando esta información, los PIB  promedio entre 2003 y 2011 para  el Distrito Federal y Chiapas son: 

In [3]:
summary(pib_estados2[,c("CHIS", "DF")], statistics=c("mean", "quantiles"), quantiles=c(0,.25,.5,.75,1)) 

      CHIS              DF         
 Min.   :194308   Min.   :1710592  
 1st Qu.:199555   1st Qu.:1830743  
 Median :202567   Median :1949102  
 Mean   :205636   Mean   :1930598  
 3rd Qu.:207209   3rd Qu.:2029147  
 Max.   :227138   Max.   :2116151  

Otras dos medidas de centralización muy utilizadas son  la moda y la mediana. La moda es el valor con la mayor frecuencia en los datos, mientras que  la mediana es el valor medio de un conjunto ordenado de datos. En nuestro ejemplo, la moda no es única ya que el PIB de un año no se repite con el mismo valor en otro período. Por otra parte, para calcular la mediana podemos ordenar los datos de menor a mayor, por ejemplo para el 2011, y obtendremos que la mediana es el valor del PIB  de 248,500 millones de pesos correspondiente al promedio de Querétaro y Sinaloa,  pues justo antes y después de esos dos estados tenemos el 50% de los datos respectivamente. Es importante hacer notar que la mediana no se verá afectada por la presencia de valores extremos ya que sólo depende del orden de los valores, más no de sus magnitudes. 

In [4]:
pib11 <- t(pib_estados2[9,])
pib11

PIB11     
AGS   135780.72
BC    364799.77
BCS    94140.27
CAM   632560.58
COAH  413397.30
COL    72700.17
CHIS  227138.20
CHIH  329662.53
DF   2116150.87
DGO   149342.96
GTO   478746.25
GRRO  183143.90
HGO   199879.64
JAL   775336.97
MEX  1134967.09
MICH  287336.40
MOR   146957.43
NAY    80124.06
NL    908844.47
OAX   193565.15
PUE   398691.02
QRO   245962.57
QROO  185014.73
SLP   238039.17
SIN   251035.48
SON   353108.97
TAB   423990.52
TAM   384890.43
TLAX   69808.87
VER   649290.61
YUC   180047.84
ZAC   117601.87

In [5]:
mean(pib11)

[1] 388189.3

In [6]:
median(pib11)


[1] 248499

La distribución de los datos se puede visualizar utilizando histogramas, los cuales presentan los porcentajes de observaciones que quedan dentro de un intervalo en particular.

In [7]:
hist(pib11)

El histograma se puede visualizar también en porcentajes en lugar de frecuencias.

In [8]:
h = hist(pib11, plot=FALSE)
h$density = h$counts/sum(h$counts)*100
plot(h,freq=FALSE)

En el histograma resultante ahora es claro que poco más del 80% de los estados mexicanos tienen un PIB que no rebase los 500,000 millones.

En los dos histogramas la forma de la gráfica muestra un gran sesgo positivo con relación al valor medio del PIB hacia valores bajos del mismo, por tal razón es relevante conocer  que tan dispersos se encuentran los datos respecto a su  media. Una de las medidas de dispersión  más frecuente es la varianza muestral (S2) y su raíz cuadrada (S) es la desviación estándar.

In [9]:
var(pib11)

PIB11       
PIB11 162578776247

In [10]:
sd(pib11)

[1] 403210.6

En los resultados precios es posible constatar que la varianza mide la dispersión pero eleva al cuadrado las unidades de medida originales, lo cual resulta difícil de interpretar; en nuestro ejemplo tenemos millones de pesos al cuadrado. Así que para interpretar ese valor, en las unidades de medida originales, es mejor considerar la desviación estándar.

Una alternativa de medición de la dispersión que tiene la virtud  de no hacer referencia a la unidad de medida es el coeficiente de variación (CV), el cual se calcula dividiendo la desviación estándar entre la media.

In [11]:
pib03 <- t(pib_estados2[1,])

cv2003 <- sd(pib_estados2[,1]) / mean(pib_estados2[,1]) *100
cv2003
cv2011 <- sd(pib_estados2[,9]) / mean(pib_estados2[,9]) *100
cv2011

[1] 10.91073

[1] 6.831922

El resultado del coeficiente de variación muestra que el PIB en 2003 varía más que el de 2011, pese a que este último presenta una varianza mayor. 

Además de las medidas de centralización y dispersión ya revisadas, podemos obtener mediciones de la forma de las distribuciones de probabilidad de nuestros datos, las cuales nos aportan información sobre la asimetría de su distribución. Las medidas de forma con las que usualmente vamos a trabajar son el sesgo y la curtosis. 

In [12]:
install.packages("moments")
library(moments) # para calcular sesgo y curtosis

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)


In [13]:
# sesgos
skewness(pib03)
skewness(pib11)

PIB03 
2.625223

PIB11 
2.785783

In [14]:
# curtosis
kurtosis(pib03)
kurtosis(pib11)

PIB03 
10.7241

PIB11 
11.8337

El sesgo (SK), mide la simetría de una distribución de frecuencias de nuestros datos con relación a la media, mientras que la curtosis (KS) mide el achatamiento o agudeza en relación con la forma que presenta una distribución normal de los datos.

Las distribuciones simétricas tienen sesgo igual a cero y sí además son mesocúrticas tienen una curtosis igual a 3, tal y como ocurre con las distribuciones normales; curtosis superiores a 3 se consideran leptocurticas e inferiores a 3 son platocuticas. De acuerdo a los resultados de nuestro ejemplo, el valor positivo que tiene el indicador de sesgo indica que la cola derecha de la distribución de los datos es larga y que gran parte de las observaciones se ubican al lado izquierdo de la media. Por su parte, las curtosis de nuestros datos son mucho mayores a 3, lo cual indica que son leptocurticas y por consiguiente presentan un pico más afilado que el de la normal lo cual es resultado de la elevada concentración de los datos en los calores bajos del PIB.

In [15]:
densidad_pib2011 <- density(pib11)

In [16]:
plot(densidad_pib2011)

## Probabilidad

La teoría de la probabilidad es fundamental para realizar inferencias de la población a partir de datos muestrales. En esta sección se establecerán algunas de las definiciones básicas.

La probabilidad del evento A esta definida por: Pr(A) y cumple con los siguientes axiomas definidos por el matemático ruso Kolmogorov:

La probabilidad para cualquier evento A es un número positivo  entre cero y uno: 0 ≤ Pr (𝐴) ≤ 1.

La probabilidad de que ocurra el evento seguro Z es la unidad: Pr(𝑍) = 1. 
La probabilidad de la unión de los eventos A1, A2, A3,... es igual a la suma de las probabilidades de los eventos individuales siempre y cuando sean mutuamente excluyentes (no pueden ocurrir al mismo tiempo)

Pr(∪𝐴𝑖) = ∑Pr(𝐴𝑖)  𝑠𝑖 𝐴𝑖 ∩𝐴𝑗 =    donde  es el evento imposible 

Los tres axiomas permiten establecer los siguientes teoremas:

Si el evento A es un subconjunto del evento B entonces la Pr (𝐴) es menor o igual a la Pr(B): 𝐴 ⊂ 𝐵 → Pr (𝐴) ≤ Pr (𝐵). 

Para cualquier evento A la probabilidad de su complemento, Pr(𝐴𝑐), es igual a: 1− Pr (𝐴).

La probabilidad del evento imposible es cero: Pr() = 0

La probabilidad de la unión de dos eventos es: 
 Pr(𝐴∪𝐵) = Pr(𝐴)+Pr(𝐵)−Pr (𝐴∩𝐵) 

Si  los eventos A y B son independientes la probabilidad de ocurrencia de un evento no influye en la del otro s la siguiente probabilidad condicional: Pr(𝐴|𝐵) = Pr (𝐴). Si no son independientes la probabilidad condicional se define de la siguiente manera: 

Pr(𝐴|𝐵) = Pr (𝐴∩𝐵) / Pr (𝐵)
 

## VARIABLE ALEATORIA 

Variables como el PIB o la inflación no son conocidas antes de que sean generadas y reportadas por las agencias gubernamentales, lo cual implica que su resultado nunca es conocido de antemano, por ello a este tipo de variables se les conoce como variables aleatorias.

Las probabilidades asociadas a una variable aleatoria se calculan a través de su función de distribución probabilística. En nuestro ejemplo, al lanzar dos monedas y donde X= salga cara. 

También es posible determinar la probabilidad de que la variable aleatoria tome valores a lo mucho iguales a x, esto es la función de densidad acumulada y se define como:  Pr (𝑋) ≤ 𝑥

Para variables aleatorias continuas no es relevante calcular la probabilidad de que X tome un valor particular x debido a que en un intervalo a,b existe un número infinito de puntos. Por ello, la cuestión relevante es calcular la probabilidad de que X tome valores en el intervalo a,b donde a<b;

Para una variable aleatoria discreta, su media o valor esperado es un promedio ponderado de sus posibles resultados, en donde el ponderador es la probabilidad asociada a cada valor.

El operador de valor esperado (E) que hemos utilizado tiene algunas propiedades interesantes: 
 
𝐸(𝑘) = 𝑘           siendo k una constante cualquiera

𝐸(𝑋 +𝑌) = 𝐸(𝑋)+𝐸(𝑌) 

𝐸(𝑋𝑌) = 𝐸(𝑋)𝐸(𝑌)   si X, Y son independientes 
 
Asimismo la varianza tiene las propiedades siguientes:

𝑉𝑎𝑟(𝑘𝑋) = 𝑘^2𝑉𝑎𝑟(𝑋)  siendo k una constante cualquiera 

𝑉𝑎𝑟(𝑋 +𝑌) = 𝑉𝑎𝑟(𝑋)+𝑉𝑎𝑟(𝑌)  si X, Y son independientes


La distribución conjunta de una variable aleatoria X y una variable aleatoria Y para el caso discreto es igual a la lista de probabilidades de ocurrencia de todos los resultados para X y Y. 

Cov(X,Y)=E(X-E(X))(Y-E(Y)) 
 
La covarianza mide la asociación lineal entre las dos variables.

El coeficiente de correlación tiene un rango que va de -1 a +1.

##  Algunas funciones de distribución particulares

En muchos casos prácticos surgen variables aleatorias con distribuciones de probabilidad similares a algunas distribuciones utilizadas cotidianamente. Veamos las más importantes para los modelos econométricos. 
 
 
### Distribución Binaria 
 
La variable aleatoria X toma únicamente valores 0 y 1 con probabilidades p y 1-p, a estas variables se les denomina variables aleatorias Bernoulli. Donde P(X=1)=p y la P(X=0)=1-p 
 
Por lo tanto, la función de probabilidad es: 
 
f(x)=P(X=x)=p^x(1-p)^1-x 
 
Un importante grupo de modelos econométricos utilizan  variables dependientes cualitativas que son codificadas como uno y cero, estos modelos se conocen como logit, probit y tobit. Su función de distribución se podría representar con una gráfica de bastón

### Distribución Binomial 
 
La variable aleatoria mide el número de éxitos en n experimentos de éxito-fracaso, iguales e independientes.

Por ejemplo, considere tres consumidores que van a una tienda de ropa y obtenga la probabilidad de que ninguno haga una compra si la probabilidad de compra es de 0.3.

En R se puede calcular esa probabilidad utilizando la siguiente instrucción: dbinom(x,n,p). Para el caso previo en R se obtiene el resultado escribiendo: 

In [17]:
dbinom(0,3,0.3)

[1] 0.343

### Distribución Poisson 
 
La variable aleatoria toma una serie de valores en un tiempo o espacio en donde el número de valores es igual a cualquier entero entre cero e infinito. La muestra, n,  es grande y la probabilidad de acierto, p, es pequeña 

Por ejemplo, suponga que se toman datos de los clientes que llegan a una ventanilla de banco durante 15 minutos en un día de la semana por la tarde. Se considera que la probabilidad de que un cliente llegue es la misma en cualquier par de períodos de igual duración y que la llegada o no de un cliente es independiente de la llegada o no en cualquier otro período de tiempo. Si por los registros del banco s esabe que en 15 minutos llegan 10 clientes, es posible plantear una función de  probabilidad de Poisson

Queremos saber la probabilidad de que lleguen exactamente cinco clientes.

In [18]:
dpois(5,10)

[1] 0.03783327

### Distribución Normal

La distribución Normal es sin duda la distribución más usual que se emplea en estadística.

La función normal depende de los valores de la media, y de la desviación estándar, que al variar generan una familia infinita de distribuciones normales. 

Para evitar construir una tabla de probabilidades cada que varían los parámetros de la función, lo que se hace es estandarizarla: Una variable aleatoria es estandarizada si se le resta su media y se divide entre su desviación estándar, lo que da como resultado una variable con media cero y varianza igual a la unidad.

In [19]:
x_norm <- seq(-3, 3, length=100)
y_norm <- dnorm(x_norm)
plot(x_norm,y_norm, type = "l", lwd = 2, axes = FALSE, xlab = "x", ylab = "Density")
axis(1, at = -3:3, labels = c("-3", "-2", "-1", "0", "1", "2", "3"))

Aproximadamente el 68% del área o probabilidad de la curva se encuentra a más menos una desviación estándar de la media, el 95.5% de probabilidad se encuentra a más menos dos desviaciones y casi toda el área entre más menos tres desviaciones. 
 
La distribución normal es muy utilizada ya que es simétrica y puede caracterizarse por su media y varianza. Además de que una propiedad importante de dos o más variables aleatorias distribuidas normalmente, con la misma media y varianza,  es que su suma ponderada se distribuye también como una normal.

In [20]:
x_dchisq <- seq(0, 20, by = 0.1)
y_dchisq <- dchisq(x_dchisq, df = 5)
plot(y_dchisq)

In [21]:
x_dchisq <- seq(0, 20, by = 0.1)
y_dchisq <- dchisq(x_dchisq, df = 50)
plot(y_dchisq)

## Distribución t de student

In [22]:
curve(dt(x, 5), from = -6, to = 6, col = "black", xlab = "x", ylab = "Density", lwd = 2)

In [23]:
curve(dt(x, 50), from = -6, to = 6, col = "black", xlab = "x", ylab = "Density", lwd = 2)

### La distribución F de Fisher

Es una combinación de dos variables chi-cuadrada

In [24]:
curve(df(x, df1=5, df2=5), from=0, to=40, xlab = "x", ylab = "Density")

In [25]:
curve(df(x, df1=50, df2=50), from=0.5, to=2.5, xlab = "x", ylab = "Density")

##  BREVE REPASO DE ÁLGEBRA DE MATRICES 

El uso de álgebra de matrices nos brinda un modo de representar y manejar datos de forma compacta. Una matriz no es más que un arreglo rectangular de elementos o números en renglones o columnas.

In [26]:
# Para introducir una matriz

A <- matrix(c(10, 20, 30, 5, 10, 40, 8, 30, 1), nrow=3, ncol=3, byrow=T)

In [27]:
A

[,1] [,2] [,3]
[1,] 10   20   30  
[2,]  5   10   40  
[3,]  8   30    1

In [28]:
B <- matrix(c(50, 80, 100, 30, 40, 50, 60, 50, 80), nrow=3, ncol=3, byrow=T)
B

[,1] [,2] [,3]
[1,] 50   80   100 
[2,] 30   40    50 
[3,] 60   50    80

In [29]:
# obtengo la transpuesta de A
t(A)

[,1] [,2] [,3]
[1,] 10    5    8  
[2,] 20   10   30  
[3,] 30   40    1

In [30]:
# sumo matrices de identicas dimensiones
t(A) + B

[,1] [,2] [,3]
[1,] 60   85   108 
[2,] 50   50    80 
[3,] 90   90    81

In [31]:
# resto matrices de identicas dimensiones
t(A) - B

[,1] [,2] [,3]
[1,] -40  -75  -92 
[2,] -10  -30  -20 
[3,] -30  -10  -79

In [32]:
# multiplico por un escalar

2 * t(A)

[,1] [,2] [,3]
[1,] 20   10   16  
[2,] 40   20   60  
[3,] 60   80    2

Una matriz  de dimensión 1xn es un vector renglón y lo representamos generalmente con letras minúsculas.
Un vector de dimensión nx1 es un vector columna.

Al multiplicar dos vectores se multiplica cada elemento del vector fila i-ésima por su correspondiente elemento en la jésima columna del segunda vector y posteriormente se suman esos productos.  
La multiplicación matricial es una generalización de la multiplicación vectorial repetida.

In [33]:
# La multiplicación matricial la podemos llevar a cabo en R con la siguiente instrucción

t(A)%*%B

[,1] [,2] [,3]
[1,] 1130 1400 1890
[2,] 3100 3500 4900
[3,] 2760 4050 5080

Se debe ser cuidadoso con R debido a que tiene dos formas de multiplicar estás matrices, la que acabamos de hacer que sigue el cálculo de algebra lineal, mientras que  t(A)*B hubiera dado lugar a una multiplicación elemento a elemento como la que se presenta enseguida:

In [34]:
t(A) * B

[,1] [,2] [,3]
[1,]  500  400  800
[2,]  600  400 1500
[3,] 1800 2000   80

De la multiplicación matricial se puede deducir: 
 
Si una matriz A es de dimensión mxn y una matriz B es de orden nxp, el producto AB es una matriz de orden mxp.  
Para poder realizar la multiplicación debe cumplirse que la dimensión columna de la primer matriz sea igual a la dimensión fila de la segunda matriz.  
 
Existe un tipo de matrices con la peculiar característica que multiplicada por sí misma, cualquier número de veces, es siempre igual a la matriz original, a estas matrices se les llama idempotentes.

La matriz identidad en su diagonal principal tiene únicamente elementos escalares iguales a la unidad y ceros fuera de ella. Dado que es una matriz cuadrada se suele representar como In cuando es de dimensión nxn o simplemente como I cuando no hay confusión acerca de su dimensión.

En R se puede generar una matriz identidad con la función diag(m), siendo m el orden de la matriz. Por ejemplo, generamos una matriz identidad de cuatro por cuatro: 

In [35]:
diag(4)

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

El determinante de A  es una función de los valores aij de la matriz.

Para calcular el determinante en R escribimos:

In [36]:
det(t(A))

[1] -3500

Ahora estamos en condiciones de calcular la inversa.

In [37]:
solve(t(A))

[,1]       [,2]        [,3] 
[1,]  0.3400000 -0.09000000 -0.02
[2,] -0.2514286  0.06571429  0.04
[3,] -0.1428571  0.07142857  0.00

Otras dos operaciones con matrices que nos serán de utilidad son la traza y el producto Kronecker. 
 
La traza de una matriz es la suma de los elementos de su diagonal principal y tiene las siguientes propiedades: 
tr(A+B)=tr(A)+tr(B) 
tr(AB)=tr(BA) 
tr(ABC)=tr(CAB)=tr(BCA) 
tr(k)=k donde k es una constante 

Es posible calcular la traza en R, por ejemplo para la matriz A tendríamos:

In [38]:
sum(diag(A))

[1] 21

El producto Kronecker nos permite multiplicar matrices que por sus dimensiones no son conformables para la multiplicación.

Para nuestras matrices A y B su producto Kronecker se obtiene en R con la siguiente instrucción: 

In [39]:
kronecker(A, B)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9]
 [1,] 500  800  1000 1000 1600 2000 1500 2400 3000
 [2,] 300  400   500  600  800 1000  900 1200 1500
 [3,] 600  500   800 1200 1000 1600 1800 1500 2400
 [4,] 250  400   500  500  800 1000 2000 3200 4000
 [5,] 150  200   250  300  400  500 1200 1600 2000
 [6,] 300  250   400  600  500  800 2400 2000 3200
 [7,] 400  640   800 1500 2400 3000   50   80  100
 [8,] 240  320   400  900 1200 1500   30   40   50
 [9,] 480  400   640 1800 1500 2400   60   50   80

En R podemos generar una nueva matriz de 2x2 con los valores de la matriz A, para no confundirla con la matriz A que hemos empleado antes ahora le llamaremos AE. La instrucción en R para generar la matriz AE es la siguiente:

In [40]:
AE <- matrix(c(4, 2, 2, 1), nrow=2, ncol=2, byrow=T)
list(AE)

[[1]]
     [,1] [,2]
[1,]    4    2
[2,]    2    1

Los valores y vectores característicos los obtenemos con la instrucción: 

In [41]:
eigen(AE)

eigen() decomposition
$values
[1] 5 0

$vectors
           [,1]       [,2]
[1,] -0.8944272  0.4472136
[2,] -0.4472136 -0.8944272
